### ISSUE TITLE
biolatency gadget not available via local-gadget 

### ISSUE THREAD

**Issue by invidian** [kinvolk/inspektor-gadget#717] opened 2022-06-29 10:06 UTC
## Description

I wanted to check something using `biolatency` gadget on my local machine, following documentation from https://kinvolk.io/docs/inspektor-gadget/latest/local-gadget/ and I got the following result:
```console
$ sudo ./local-gadget
WARN[0000] Runtime enricher (containerd): failed to get current containers
WARN[0000] Runtime enricher (cri-o): failed to get current containers
» list-gadgets
audit-seccomp
dns
seccomp
snisnoop
socket-collector
```

## Impact

Unable to use `biolatency` gadget via `local-gadget`.

## Environment and steps to reproduce

1. Cloned repository and checkout out 008667ba8192f53c8af25d52e2324e2d06708020.
2. Ran `make local-gadget`.
3. Ran commands above.

## Expected behavior

Trace to be successfully created.

## Additional information

Tested on Arch Linux as a host.

**Comment by blanquicet** [comment] 2022-06-29 10:25
Thanks @invidian!

The issue is that the documentation does not follow the current implementation. I noticed multiple misalignments:

- As you said, the biolatency gadget is not currently supported by local-gadget but it is present in [the local-gadget doc](https://github.com/kinvolk/inspektor-gadget/blob/d4000354caac5fb58df556942b3539dbadf41013/docs/local-gadget.md#biolatency).
- The example for the audit-seccomp is in [the main guides](https://github.com/kinvolk/inspektor-gadget/blob/d4000354caac5fb58df556942b3539dbadf41013/docs/guides/audit/seccomp.md#with-local-gadget) but it is not present in  [the local-gadget doc](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/local-gadget.md).
- There are no examples for the socket-collector and snisnoop gadgets with local-gadget. Neither in the [the main guides](https://github.com/kinvolk/inspektor-gadget/blob/d4000354caac5fb58df556942b3539dbadf41013/docs/guides) nor in the [the local-gadget doc](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/local-gadget.md). 

In general, we need to define where to put the local-gadget examples: (1) together with the kubectl-gadget examples or (2) in a dedicated document for local-gadget.

**Comment by invidian** [comment] 2022-06-29 10:26
Thanks for looking into it @blanquicet. Should I open a separate issue then if I would like `biolatency` to be available as a local gadget?

**Comment by alban** [comment] 2022-06-29 10:39
As a quick workaround (but currently, that would only work if bcc is installed on your computer, see https://github.com/kinvolk/inspektor-gadget/issues/512):

```patch
--- a/pkg/gadget-collection/gadget-collection.go
+++ b/pkg/gadget-collection/gadget-collection.go
@@ -71,6 +71,7 @@ func TraceFactories() map[string]gadgets.TraceFactory {
 
 func TraceFactoriesForLocalGadget() map[string]gadgets.TraceFactory {
        return map[string]gadgets.TraceFactory{
+               "biolatency":       biolatency.NewFactory(),
                "audit-seccomp":    auditseccomp.NewFactory(),
                "dns":              dns.NewFactory(),
                "socket-collector": socketcollector.NewFactory(),
```

```bash
$ make local-gadget
...
$ sudo ./local-gadget --runtimes docker
» create biolatency trace1 
State: Started
» sleep 10
Error: unknown command "sleep" for ""
Run ' --help' for usage.
unknown command "sleep" for ""
» operation trace1 stop 
State: Completed
Tracing block device I/O... Hit Ctrl-C to end.

     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 13       |***********                             |
        64 -> 127        : 33       |*****************************           |
       128 -> 255        : 4        |***                                     |
       256 -> 511        : 20       |*****************                       |
       512 -> 1023       : 18       |****************                        |
      1024 -> 2047       : 2        |*                                       |
      2048 -> 4095       : 45       |****************************************|

»  
```

**Comment by blanquicet** [comment] 2022-08-31 11:24
Closed in favour of https://github.com/kinvolk/inspektor-gadget/issues/865.

**Closed by blanquicet** 2022-08-31 11:24 UTC
Labels: good first issue, area/documentation, area/local-gadget
